### ISSUE TITLE
Impostazione parametri simulazione

### ISSUE THREAD

**Issue by GZaccaroni** [GZaccaroni/pps-warverse#12]
Io come utente avanzato voglio poter impostare i parametri degli stati tramite codice Scala in modo da poterli poi vedere nella simulazione

**Tasks:**

- [ ] Caricamento di nome, popolazione, risorse, esercito
- [ ] Caricamento delle coordinate dei vertici dell'area dello statoC
- [ ] Caricamento delle relazioni interstatali
